-   Template: 'qtci-linux-Ubuntu-18.04-x86_64'
    Compiler: 'GCC'
    Configure arguments: '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_EXAMPLES=OFF -DFEATURE_developer_build=ON'
-   Template: 'qtci-linux-openSUSE-15.0-x86_64'
    Compiler: 'ICC_18'
    Configure arguments: '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF'
-   Template: 'qtci-macos-10.13-x86_64-2'
    Compiler: 'Clang'
    Configure arguments: '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_EXAMPLES=OFF -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode10.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12'
-   Template: 'qtci-windows-10-x86_64-14'
    Compiler: 'MSVC2017'
    Configure arguments: '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_EXAMPLES=OFF -DCMAKE_TOOLCHAIN_FILE={{.Env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake'
