Version: 2
Configurations:
-
    Template: 'qtci-linux-Ubuntu-18.04-x86_64'
    Compiler: 'GCC'
    Configure arguments: '-DBUILD_EXAMPLES=ON -DFEATURE_developer_build=ON'
-
    Template: 'qtci-linux-openSUSE-15.0-x86_64'
    Compiler: 'ICC_18'
    Configure arguments: '-DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF'
-
    Template: 'qtci-macos-10.13-x86_64-2'
    Compiler: 'Clang'
    Configure arguments: '-DBUILD_EXAMPLES=OFF -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode10.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12'
-
    Template: 'qtci-windows-10-x86_64-14'
    Compiler: 'MSVC2017'
    Configure arguments: '-DBUILD_EXAMPLES=OFF -DCMAKE_TOOLCHAIN_FILE={{.Env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake'
-
    Template: 'qtci-linux-RHEL-7.6-x86_64'
    Compiler: 'GCC'
    Configure arguments: '-DBUILD_EXAMPLES=OFF'
-
    Template: 'qtci-linux-RHEL-7.6-x86_64'
    Target os: 'Android_ANY'
    Target arch: 'arm64'
    Compiler: 'GCC'
    Target compiler: 'Clang'
    Configure arguments: '-DBUILD_EXAMPLES=OFF'
    Environment variables: ['TARGET_CONFIGURE_ARGS=-DBUILD_EXAMPLES=OFF -DCMAKE_TOOLCHAIN_FILE={{.Env.ANDROID_NDK_ROOT}}/build/cmake/android.toolchain.cmake -DANDROID_SDK_ROOT={{.Env.ANDROID_SDK_HOME}} -DANDROID_ABI=arm64-v8a -DVCPKG_TARGET_TRIPLET=arm64-android']
