version: 2
accept_configuration:
  condition: property
  property: host.os
  equals_property: target.os

instructions:
  Build:
    - !include "{{qt/qtbase}}/prepare_building_env.yaml"
    - type: MakeDirectory
      directory: .git
    - type: SetBuildDirectory
      directory: "{{.SourceDir}}"
    - type: ChangeDirectory
      directory: "{{.BuildDir}}"
    - type: ExecuteCommand
      command: "{{.Env.ENV_PREFIX}} cmake {{.Env.CONFIGURE_ARGS}} -DCMAKE_INSTALL_PREFIX:PATH={{.InstallDir}} -DBUILD_TESTING=OFF {{.SourceDir}}"
      executeCommandArgumentSplitingBehavior: SplitAfterVariableSubstitution
      maxTimeInSeconds: 6000
      maxTimeBetweenOutput: 1200
      userMessageOnFailure: >
        Failed to call cmake.

  Test:
    - type: EnvironmentVariable
      variableName: Dummy
      variableValue: dummy
