version: 1
accept_configuration:
  condition: property
  property: host.os
  equals_property: target.os

build_instructions:
  - type: EnvironmentVariable
    variableName: Dummy
    variableValue: dummy
